### PR TITLE
fix for aot compilation to be used when using in other repo as dependency 

### PR DESCRIPTION
**Pull request by hakhan88**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hakhan88 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-flo&pullRequestId=57)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-flo&pullRequestId=57) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hakhan88 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-flo&pullRequestId=57)!

**Comment by BoykoAlex** [comment]
@hakhan88 Thanks for the PR, it'd require a few adjustments. The built js code in `out-tsc` and built angular module code under `dist` should not be in the git repo. Once we merge your PR we can make a 0.8.10 release for you to consume your fix.

**Comment by hakhan88** [comment]
Thanks for the review. Made the changes and pushed to the branch. Please let me know if naything further is required from my end. Thanks !

**Comment by BoykoAlex** [comment]
@hakhan88 LGTM merged. BTW, how do you consume Flo in your repo? As npm dependency on specific version? If you'd like to depend on Flo from master you can simply put `"spring-flo": "https://github.com/spring-projects/spring-flo#master",` in your `package.json`. When you `npm install` in your project with such dependency it'll build Flo during `npm install`...

**Comment by hakhan88** [comment]
thanks for the merge. I normally include it in the dependency for spring-flo on specific version. i'll try out the way you suggested above.

**Pull request merged**
